######################################################################
# Automatically generated by qmake (2.01a) Mon Jul 25 13:35:11 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += . ../../src

# Input
SOURCES += RWMutex.cpp

LIBS += -L/mnt/server0/users/zhaoyong/Program/Apps/PIS-1.1.0/Thirdparty/PIL-1.1.0/libs -lpi_base

QMAKE_CXXFLAGS += -std=c++11
