TOPDIR 	?= ../..
MAKE_TYPE =bin
LIB_PREFIX=
BUILD_PATH=$(TOPDIR)/build/$(HereFolderName)

COMPILEFLAGS= $(ALL_CFLAGS)
LINKFLAGS   = $(ALL_LDFLAGS)

OUTPUT      = ObstacleAvoidance
EXEEXT      =  

include $(TOPDIR)/scripts/make.conf


